version: '3.8'

services:
  app:
    build: .
    image: iris-api:latest
    ports:
      - "5000:5000"
    networks:
      - app-network
    environment:
      - FLASK_ENV=production
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge